from __future__ import annotations

from copy import deepcopy
from typing import Any

from app.schemas.models import (
    BuyerAcceptanceSpec,
    BuyerRequirement,
    Company,
    ImpactMethodology,
    Material,
    MaterialLot,
    MaterialUse,
    QualityEvidence,
    ScoringConfig,
    User,
    WasteListing,
)

DEMO_TIMESTAMP = "2026-08-12T09:30:00+05:30"

# These are city-centre/sample coordinates for a fictional demonstration only.
CITY_COORDINATES: dict[str, tuple[float, float]] = {
    "noida": (28.5355, 77.3910),
    "ghaziabad": (28.6692, 77.4538),
    "new delhi": (28.6139, 77.2090),
    "delhi": (28.6139, 77.2090),
    "gurugram": (28.4595, 77.0266),
    "gurgaon": (28.4595, 77.0266),
    "faridabad": (28.4089, 77.3178),
    "manesar": (28.3553, 76.9369),
    "bhiwadi": (28.2100, 76.8606),
    "sonipat": (28.9931, 77.0151),
}


def city_coordinates(city: str) -> tuple[float, float] | None:
    normalized = city.strip().lower()
    if normalized in CITY_COORDINATES:
        return CITY_COORDINATES[normalized]
    for known_city, coords in CITY_COORDINATES.items():
        if known_city in normalized or normalized in known_city:
            return coords
    return None


def build_seed_data() -> dict[str, Any]:
    pet_uses = [
        MaterialUse(
            id="use-pet-recycling",
            material_id="mat-pet",
            title="Recycled PET feedstock",
            description="Potential use after buyer-side sorting, processing, and quality checks.",
            pathway_type="mechanical_recycling",
            recovery_factor=0.85,
            virgin_displacement_factor=0.85,
            assumptions={
                "label": "Illustrative / Demo Data",
                "recovery_note": "Illustrative recovery factor; not a yield guarantee.",
            },
        ),
        MaterialUse(
            id="use-pet-fibre",
            material_id="mat-pet",
            title="Polyester fibre feedstock",
            description="Potential downstream use where the recycler and buyer confirm suitability.",
            pathway_type="secondary_feedstock",
            recovery_factor=0.76,
            virgin_displacement_factor=0.70,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
        MaterialUse(
            id="use-pet-products",
            material_id="mat-pet",
            title="Plastic processing feedstock",
            description="Potential use in suitable non-food processing pathways after verification.",
            pathway_type="secondary_feedstock",
            recovery_factor=0.70,
            virgin_displacement_factor=0.65,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
    ]
    textile_uses = [
        MaterialUse(
            id="use-textile-yarn",
            material_id="mat-cotton-textile",
            title="Recycled yarn feedstock",
            description="Potential use after fibre sorting and buyer quality checks.",
            pathway_type="fibre_recycling",
            recovery_factor=0.72,
            virgin_displacement_factor=0.70,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
        MaterialUse(
            id="use-textile-insulation",
            material_id="mat-cotton-textile",
            title="Insulation material",
            description="Potential nonwoven or insulation pathway subject to processing requirements.",
            pathway_type="nonwoven_recovery",
            recovery_factor=0.68,
            virgin_displacement_factor=0.55,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
        MaterialUse(
            id="use-textile-wipes",
            material_id="mat-cotton-textile",
            title="Industrial wiping material",
            description="Potential use where cleanliness and fibre composition are verified.",
            pathway_type="reuse_recovery",
            recovery_factor=0.80,
            virgin_displacement_factor=0.50,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
    ]
    paper_uses = [
        MaterialUse(
            id="use-paper-board",
            material_id="mat-paper-cardboard",
            title="Recycled paperboard feedstock",
            description="Potential pulping route subject to moisture and contamination checks.",
            pathway_type="paper_recycling",
            recovery_factor=0.82,
            virgin_displacement_factor=0.75,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
        MaterialUse(
            id="use-paper-pulp",
            material_id="mat-paper-cardboard",
            title="Moulded pulp products",
            description="Potential use after buyer-side fibre and contamination evaluation.",
            pathway_type="paper_recycling",
            recovery_factor=0.70,
            virgin_displacement_factor=0.62,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
    ]
    steel_uses = [
        MaterialUse(
            id="use-steel-remelt",
            material_id="mat-steel-scrap",
            title="Steel re-melt feedstock",
            description="Potential use after grade separation and processor acceptance checks.",
            pathway_type="metal_recycling",
            recovery_factor=0.92,
            virgin_displacement_factor=0.90,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
        MaterialUse(
            id="use-steel-blend",
            material_id="mat-steel-scrap",
            title="Secondary scrap blend",
            description="Potential processing pathway subject to buyer specifications.",
            pathway_type="metal_recycling",
            recovery_factor=0.86,
            virgin_displacement_factor=0.80,
            assumptions={"label": "Illustrative / Demo Data"},
        ),
    ]

    materials = [
        Material(
            id="mat-pet",
            canonical_name="PET industrial scrap",
            category="Plastic",
            aliases=["pet scrap", "pet manufacturing scrap", "pet waste", "polyethylene terephthalate"],
            quality_scale=["unknown", "mixed", "standard", "industrial", "premium"],
            notes="Controlled MVP material. Quality remains Not verified unless documentary verification is recorded.",
            uses=pet_uses,
        ),
        Material(
            id="mat-cotton-textile",
            canonical_name="Cotton textile cutting waste",
            category="Textile",
            aliases=["cotton cutting waste", "textile cutting waste", "cotton scraps", "fabric offcuts"],
            quality_scale=["unknown", "mixed", "standard", "industrial", "premium"],
            notes="Controlled MVP material. Composition and cleanliness require buyer verification.",
            uses=textile_uses,
        ),
        Material(
            id="mat-paper-cardboard",
            canonical_name="Corrugated cardboard and paper trim",
            category="Paper / Cardboard",
            aliases=["cardboard waste", "occ", "paper trim", "corrugated scrap"],
            quality_scale=["unknown", "mixed", "standard", "industrial", "premium"],
            notes="Controlled MVP material. Moisture and contamination must be checked by buyer.",
            uses=paper_uses,
        ),
        Material(
            id="mat-steel-scrap",
            canonical_name="Mild-steel fabrication scrap",
            category="Metal",
            aliases=["steel scrap", "mild steel scrap", "metal fabrication scrap", "ms scrap"],
            quality_scale=["unknown", "mixed", "standard", "industrial", "premium"],
            notes="Controlled MVP material. Grade separation and contaminant checks are required.",
            uses=steel_uses,
        ),
    ]

    companies = [
        Company(
            id="comp-gen-pet",
            owner_user_id="user-generator",
            name="Noida PackForm Industries",
            company_type="generator",
            city="Noida",
            address_label="Sector 63, Noida — Demo location",
            latitude=28.5355,
            longitude=77.3910,
        ),
        Company(
            id="comp-gen-textile",
            name="LoomLink Textiles",
            company_type="generator",
            city="Ghaziabad",
            address_label="Sahibabad, Ghaziabad — Demo location",
            latitude=28.6730,
            longitude=77.4470,
        ),
        Company(
            id="comp-gen-paper",
            name="GreenFold Paperboard",
            company_type="generator",
            city="Faridabad",
            address_label="Sector 24, Faridabad — Demo location",
            latitude=28.4050,
            longitude=77.3100,
        ),
        Company(
            id="comp-gen-metal",
            name="Atlas Fabrication Works",
            company_type="generator",
            city="Gurugram",
            address_label="Udyog Vihar, Gurugram — Demo location",
            latitude=28.5000,
            longitude=77.0900,
        ),
        Company(
            id="comp-buyer-pet-top",
            owner_user_id="user-buyer",
            name="ReLoop Polymers",
            company_type="recycler",
            city="Manesar",
            address_label="Industrial Area, Manesar — Demo location",
            latitude=28.3553,
            longitude=76.9369,
        ),
        Company(
            id="comp-buyer-pet-nearby",
            name="NorthStar Reclaim",
            company_type="recycler",
            city="Ghaziabad",
            address_label="Loni, Ghaziabad — Demo location",
            latitude=28.7240,
            longitude=77.4260,
        ),
        Company(
            id="comp-buyer-pet-volume",
            name="MouldCycle Materials",
            company_type="processor",
            city="Bhiwadi",
            address_label="RIICO Industrial Area, Bhiwadi — Demo location",
            latitude=28.2100,
            longitude=76.8606,
        ),
        Company(
            id="comp-buyer-textile",
            name="ThreadAgain Fibres",
            company_type="recycler",
            city="Noida",
            address_label="Sector 68, Noida — Demo location",
            latitude=28.6020,
            longitude=77.3650,
        ),
        Company(
            id="comp-buyer-paper",
            name="RenewBoard Papers",
            company_type="processor",
            city="Delhi",
            address_label="Okhla, Delhi — Demo location",
            latitude=28.5310,
            longitude=77.2700,
        ),
        Company(
            id="comp-buyer-metal",
            name="ForgeBack Metals",
            company_type="processor",
            city="Faridabad",
            address_label="Ballabgarh, Faridabad — Demo location",
            latitude=28.3400,
            longitude=77.3300,
        ),
    ]

    users = [
        User(
            id="user-generator",
            full_name="Aarav Sharma",
            email="generator@circularmatch.demo",
            role="generator",
            company_id="comp-gen-pet",
        ),
        User(
            id="user-buyer",
            full_name="Kiran Mehta",
            email="buyer@circularmatch.demo",
            role="buyer",
            company_id="comp-buyer-pet-top",
        ),
        User(
            id="user-admin",
            full_name="Rhea Kapoor",
            email="admin@circularmatch.demo",
            role="admin",
            company_id=None,
        ),
    ]

    listings = [
        WasteListing(
            id="listing-pet-demo",
            company_id="comp-gen-pet",
            material_id="mat-pet",
            raw_description="Illustrative demo listing: approximately 2.6 tonnes of clean PET manufacturing scrap each week in Noida.",
            source="demo",
            quantity_kg=2600,
            frequency="weekly",
            normalized_kg_per_week=2600,
            quality_grade="industrial",
            quality_verified=False,
            quality_notes="Supplier-declared clean industrial scrap. Certification not supplied in demo data.",
            availability="Every Monday",
            city="Noida",
            latitude=28.5355,
            longitude=77.3910,
            asking_price_per_kg=14.0,
            disposal_cost_per_kg=8.0,
            selected_use_id="use-pet-recycling",
            is_demo=True,
            created_at=DEMO_TIMESTAMP,
        ),
        WasteListing(
            id="listing-textile-demo",
            company_id="comp-gen-textile",
            material_id="mat-cotton-textile",
            raw_description="Illustrative demo listing: cotton textile cutting waste from a Ghaziabad factory.",
            source="demo",
            quantity_kg=4200,
            frequency="weekly",
            normalized_kg_per_week=4200,
            quality_grade="standard",
            quality_verified=False,
            quality_notes="Supplier-declared cotton cutting waste; fibre composition is not verified.",
            availability="Weekly dispatch window",
            city="Ghaziabad",
            latitude=28.6730,
            longitude=77.4470,
            asking_price_per_kg=9.0,
            disposal_cost_per_kg=4.5,
            selected_use_id="use-textile-yarn",
            is_demo=True,
            created_at=DEMO_TIMESTAMP,
        ),
        WasteListing(
            id="listing-paper-demo",
            company_id="comp-gen-paper",
            material_id="mat-paper-cardboard",
            raw_description="Illustrative demo listing: corrugated cardboard and paper trim from Faridabad.",
            source="demo",
            quantity_kg=6000,
            frequency="weekly",
            normalized_kg_per_week=6000,
            quality_grade="industrial",
            quality_verified=False,
            quality_notes="Moisture and contamination not verified in demo data.",
            availability="Weekdays",
            city="Faridabad",
            latitude=28.4050,
            longitude=77.3100,
            asking_price_per_kg=6.5,
            disposal_cost_per_kg=3.0,
            selected_use_id="use-paper-board",
            is_demo=True,
            created_at=DEMO_TIMESTAMP,
        ),
        WasteListing(
            id="listing-steel-demo",
            company_id="comp-gen-metal",
            material_id="mat-steel-scrap",
            raw_description="Illustrative demo listing: mild-steel fabrication offcuts from Gurugram.",
            source="demo",
            quantity_kg=2800,
            frequency="weekly",
            normalized_kg_per_week=2800,
            quality_grade="industrial",
            quality_verified=False,
            quality_notes="Supplier-declared mild-steel fabrication scrap; grade verification pending.",
            availability="Fortnightly collections",
            city="Gurugram",
            latitude=28.5000,
            longitude=77.0900,
            asking_price_per_kg=28.0,
            disposal_cost_per_kg=6.0,
            selected_use_id="use-steel-remelt",
            is_demo=True,
            created_at=DEMO_TIMESTAMP,
        ),
    ]

    requirements = [
        BuyerRequirement(
            id="req-pet-top",
            company_id="comp-buyer-pet-top",
            material_id="mat-pet",
            minimum_quantity_kg_week=2000,
            maximum_quantity_kg_week=5000,
            minimum_quality_grade="industrial",
            maximum_distance_km=150,
            target_price_per_kg=17.5,
            allow_partial_quantity=True,
            city="Manesar",
            latitude=28.3553,
            longitude=76.9369,
            created_at=DEMO_TIMESTAMP,
        ),
        BuyerRequirement(
            id="req-pet-nearby",
            company_id="comp-buyer-pet-nearby",
            material_id="mat-pet",
            minimum_quantity_kg_week=800,
            maximum_quantity_kg_week=1800,
            minimum_quality_grade="industrial",
            maximum_distance_km=100,
            target_price_per_kg=12.5,
            allow_partial_quantity=True,
            city="Ghaziabad",
            latitude=28.7240,
            longitude=77.4260,
            created_at=DEMO_TIMESTAMP,
        ),
        BuyerRequirement(
            id="req-pet-volume",
            company_id="comp-buyer-pet-volume",
            material_id="mat-pet",
            minimum_quantity_kg_week=6000,
            maximum_quantity_kg_week=10000,
            minimum_quality_grade="industrial",
            maximum_distance_km=70,
            target_price_per_kg=10.5,
            allow_partial_quantity=True,
            city="Bhiwadi",
            latitude=28.2100,
            longitude=76.8606,
            created_at=DEMO_TIMESTAMP,
        ),
        BuyerRequirement(
            id="req-textile",
            company_id="comp-buyer-textile",
            material_id="mat-cotton-textile",
            minimum_quantity_kg_week=2500,
            maximum_quantity_kg_week=6000,
            minimum_quality_grade="standard",
            maximum_distance_km=120,
            target_price_per_kg=11.0,
            city="Noida",
            latitude=28.6020,
            longitude=77.3650,
            created_at=DEMO_TIMESTAMP,
        ),
        BuyerRequirement(
            id="req-paper",
            company_id="comp-buyer-paper",
            material_id="mat-paper-cardboard",
            minimum_quantity_kg_week=3500,
            maximum_quantity_kg_week=9000,
            minimum_quality_grade="standard",
            maximum_distance_km=100,
            target_price_per_kg=8.5,
            city="Delhi",
            latitude=28.5310,
            longitude=77.2700,
            created_at=DEMO_TIMESTAMP,
        ),
        BuyerRequirement(
            id="req-steel",
            company_id="comp-buyer-metal",
            material_id="mat-steel-scrap",
            minimum_quantity_kg_week=1500,
            maximum_quantity_kg_week=5000,
            minimum_quality_grade="industrial",
            maximum_distance_km=100,
            target_price_per_kg=34.0,
            city="Faridabad",
            latitude=28.3400,
            longitude=77.3300,
            created_at=DEMO_TIMESTAMP,
        ),
    ]

    lots = [
        MaterialLot(
            id="lot-pet-demo",
            listing_id="listing-pet-demo",
            lot_code="PET-NOI-W33",
            available_quantity_kg=2600,
            material_form="Manufacturing trim",
            source_status="pre_consumer",
            colour="Clear",
            packaging="Baled sacks",
            storage_condition="Covered indoor storage; supplier-declared dry condition.",
            sample_available=True,
            compliance_triage="not_assessed",
            declared_spec={
                "supplier_statement": "Clean PET manufacturing trim; composition and contamination are not independently verified.",
                "intended_route": "Potential non-food mechanical recycling pathway only.",
            },
            evidence_ids=["evidence-pet-declaration", "evidence-pet-photo"],
            created_at=DEMO_TIMESTAMP,
        ),
        MaterialLot(
            id="lot-textile-demo",
            listing_id="listing-textile-demo",
            lot_code="TEX-GZB-W33",
            available_quantity_kg=4200,
            material_form="Cutting offcuts",
            source_status="pre_consumer",
            colour="Mixed light colours",
            packaging="Compressed bags",
            storage_condition="Indoor storage; fibre blend not independently verified.",
            sample_available=True,
            compliance_triage="not_assessed",
            declared_spec={"supplier_statement": "Cotton cutting waste claimed by supplier; blend verification pending."},
            evidence_ids=["evidence-textile-declaration"],
            created_at=DEMO_TIMESTAMP,
        ),
        MaterialLot(
            id="lot-paper-demo",
            listing_id="listing-paper-demo",
            lot_code="PAPER-FBD-W33",
            available_quantity_kg=6000,
            material_form="Corrugated trim",
            source_status="pre_consumer",
            colour="Brown kraft",
            packaging="Baled",
            storage_condition="Covered warehouse storage; moisture not independently verified.",
            sample_available=False,
            compliance_triage="not_assessed",
            declared_spec={"supplier_statement": "Corrugated cardboard and paper trim."},
            evidence_ids=["evidence-paper-declaration"],
            created_at=DEMO_TIMESTAMP,
        ),
        MaterialLot(
            id="lot-steel-demo",
            listing_id="listing-steel-demo",
            lot_code="STEEL-GGN-W33",
            available_quantity_kg=2800,
            material_form="Fabrication offcuts",
            source_status="pre_consumer",
            colour="Uncoated grey; supplier-declared",
            packaging="Loose bin collection",
            storage_condition="Covered yard; grade/alloy confirmation pending.",
            sample_available=True,
            compliance_triage="not_assessed",
            declared_spec={"supplier_statement": "Mild-steel fabrication offcuts; grade verification pending."},
            evidence_ids=["evidence-steel-declaration"],
            created_at=DEMO_TIMESTAMP,
        ),
    ]

    evidence = [
        QualityEvidence(
            id="evidence-pet-declaration",
            lot_id="lot-pet-demo",
            evidence_type="supplier_declaration",
            title="Supplier declaration — PET manufacturing trim",
            issuer="Noida PackForm Industries",
            status="self_declared",
            summary="Supplier describes the lot as clean industrial PET manufacturing trim. This is not a laboratory result or composition certificate.",
            created_at=DEMO_TIMESTAMP,
        ),
        QualityEvidence(
            id="evidence-pet-photo",
            lot_id="lot-pet-demo",
            evidence_type="photo",
            title="Lot photo record — demo placeholder",
            issuer="Noida PackForm Industries",
            status="uploaded",
            summary="Demo placeholder for visual lot evidence. Images do not verify composition or contamination.",
            document_name="pet-lot-demo-photo.jpg",
            created_at=DEMO_TIMESTAMP,
        ),
        QualityEvidence(
            id="evidence-textile-declaration",
            lot_id="lot-textile-demo",
            evidence_type="supplier_declaration",
            title="Supplier declaration — textile cutting waste",
            issuer="LoomLink Textiles",
            status="self_declared",
            summary="Supplier describes cotton cutting waste; fibre blend and cleanliness remain unverified.",
            created_at=DEMO_TIMESTAMP,
        ),
        QualityEvidence(
            id="evidence-paper-declaration",
            lot_id="lot-paper-demo",
            evidence_type="supplier_declaration",
            title="Supplier declaration — corrugated trim",
            issuer="GreenFold Paperboard",
            status="self_declared",
            summary="Supplier describes corrugated cardboard/paper trim; moisture and contamination remain unverified.",
            created_at=DEMO_TIMESTAMP,
        ),
        QualityEvidence(
            id="evidence-steel-declaration",
            lot_id="lot-steel-demo",
            evidence_type="supplier_declaration",
            title="Supplier declaration — fabrication offcuts",
            issuer="Atlas Fabrication Works",
            status="self_declared",
            summary="Supplier describes mild-steel fabrication offcuts; grade/alloy verification remains pending.",
            created_at=DEMO_TIMESTAMP,
        ),
    ]

    acceptance_specs = [
        BuyerAcceptanceSpec(
            id="spec-pet-top",
            buyer_requirement_id="req-pet-top",
            accepted_forms=["Manufacturing trim", "Regrind", "Sheet scrap"],
            accepted_colours=["Clear", "Transparent light blue"],
            prohibited_materials=["PVC", "PETG", "Free-flowing liquids"],
            required_evidence_status="self_declared",
            requires_sample=True,
            available_capacity_kg_week=5000,
            route_note="Potential non-food mechanical recycling feedstock only, subject to buyer inspection and sample approval.",
            review_note="Demo buyer acceptance template — not a universal PET specification.",
            updated_at=DEMO_TIMESTAMP,
        ),
        BuyerAcceptanceSpec(
            id="spec-pet-nearby",
            buyer_requirement_id="req-pet-nearby",
            accepted_forms=["Manufacturing trim", "Regrind"],
            accepted_colours=["Clear"],
            prohibited_materials=["PVC", "PETG", "Mixed polymer scrap"],
            required_evidence_status="reviewed",
            requires_sample=True,
            available_capacity_kg_week=1800,
            route_note="Requires a reviewed evidence record before commercial discussion.",
            review_note="Demo stricter-spec buyer template.",
            updated_at=DEMO_TIMESTAMP,
        ),
        BuyerAcceptanceSpec(
            id="spec-pet-volume",
            buyer_requirement_id="req-pet-volume",
            accepted_forms=["Manufacturing trim", "Regrind"],
            accepted_colours=[],
            prohibited_materials=["PVC", "PETG"],
            required_evidence_status="self_declared",
            requires_sample=True,
            available_capacity_kg_week=10000,
            route_note="Large-volume route; quantity coordination and sample review are required.",
            review_note="Demo buyer acceptance template.",
            updated_at=DEMO_TIMESTAMP,
        ),
        BuyerAcceptanceSpec(
            id="spec-textile",
            buyer_requirement_id="req-textile",
            accepted_forms=["Cutting offcuts"],
            accepted_colours=[],
            prohibited_materials=["Wet material", "Medical textiles"],
            required_evidence_status="self_declared",
            requires_sample=True,
            available_capacity_kg_week=6000,
            route_note="Potential fibre-recycling route pending sample and fibre composition review.",
            updated_at=DEMO_TIMESTAMP,
        ),
        BuyerAcceptanceSpec(
            id="spec-paper",
            buyer_requirement_id="req-paper",
            accepted_forms=["Corrugated trim", "Baled cardboard"],
            accepted_colours=["Brown kraft"],
            prohibited_materials=["Wet material", "Food residue"],
            required_evidence_status="self_declared",
            requires_sample=False,
            available_capacity_kg_week=9000,
            route_note="Potential paperboard route pending buyer moisture/contamination review.",
            updated_at=DEMO_TIMESTAMP,
        ),
        BuyerAcceptanceSpec(
            id="spec-steel",
            buyer_requirement_id="req-steel",
            accepted_forms=["Fabrication offcuts", "Turnings"],
            accepted_colours=[],
            prohibited_materials=["Sealed containers", "Oily residue"],
            required_evidence_status="self_declared",
            requires_sample=True,
            available_capacity_kg_week=5000,
            route_note="Potential re-melt feedstock pending grade and coating inspection.",
            updated_at=DEMO_TIMESTAMP,
        ),
    ]

    impact_methodologies = [
        ImpactMethodology(
            id="method-demo-impact-v1",
            name="CircularMatch illustrative pathway scenario",
            version="demo-impact-v1",
            functional_unit="1 kg of the listed material lot allocated to the matched buyer route",
            system_boundary="Illustrative scenario from listed lot through demo transport and assumed recovery pathway; not a full lifecycle assessment.",
            factor_source="Seeded CircularMatch demo assumptions only — replace with reviewed, route-specific sources before external reporting.",
            data_quality_tier="demo_scenario",
            notes="Potential avoided-emissions scenarios are presented separately from a verified GHG inventory.",
        )
    ]

    return {
        "materials": materials,
        "companies": [],
        "users": [],
        "listings": [],
        "requirements": [],
        "lots": [],
        "evidence": [],
        "acceptance_specs": [],
        "impact_methodologies": impact_methodologies,
        "sample_requests": [],
        "offers": [],
        "shipments": [],
        "audit_events": [],
        "scoring_config": ScoringConfig(),
        "transactions": [],
    }


def fresh_seed_data() -> dict[str, Any]:
    """Return a deep copy so a demo reset starts from a predictable dataset."""
    return deepcopy(build_seed_data())
